{{- if .Values.ingress.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/nginx.conf
          subPath: nginx.conf
        - name: app-code
          mountPath: /var/www/html
        command:  
        - /bin/sh
        - -c
        - |
          rm -f /etc/nginx/conf.d/default.conf && chown -R 1000:www-data /var/www/html && nginx -g 'daemon off;'
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: app-code
        hostPath:
          path: /home/cba/projet/laravel-helm-mongo-cluster-demo/backend
{{- end }}