{{- if .Values.laravel.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: laravel-service
spec:
  type: ClusterIP
  selector:
    app: laravel
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: fpm
{{- end }} 
